"""
Pushes/pulls the fetched market-data CSVs (data/prices, data/dividends,
data/institutional, data/market_value, data/news) to/from the same
private GitHub repo already used for accounts (user_store.py) and the
shared ticker registry (config.py) -- see github_json_store.py, which
all three of these modules share.

Why this exists (2026-09-11): every fetch script (price_data.py,
dividend_data.py, institutional_data.py, market_value_data.py,
news_data.py) writes ONLY to local data/<category>/*.csv, which
Streamlit Community Cloud wipes on every redeploy/sleep-wake -- exactly
the same failure mode already found and fixed for users.json and
watchlist.json, except this data is far more expensive to lose. Reported
live: a user ran the full 三大法人 (institutional) backfill -- 700+
throttled TWSE requests, over an hour -- it completed with no error, and
the data was gone again by the next visit. institutional_data.py already
checkpoints its progress to local disk every 20 requests, which protects
against losing everything if the SCRIPT crashes mid-run, but not against
the CONTAINER itself getting recycled sometime during or after that
hour, which wipes the checkpoints too.

Design, deliberately different from user_store.py's/config.py's
per-write sync:
- PUSH happens once at the END of a fetch script's run() (app.py calls
  push_category() right after a successful run_and_log()/
  run_parallel_and_log(); main.py does the same after a standalone
  `python main.py` run) -- not after every incremental local checkpoint.
  Syncing on every checkpoint would add GitHub round-trips throughout an
  already rate-limited hour-long run for comparatively little benefit:
  the local checkpoint already protects a mid-run crash that leaves the
  container itself intact, so what actually needed fixing was the case
  that was reported -- a run that finished successfully, then lost to a
  restart before anyone downloaded it.
- PULL happens once per running process (mirroring config.WATCHLIST's
  own import-time load) -- call pull_all() early in app.py so a fresh or
  restarted container restores whatever was last pushed BEFORE the user
  even notices data is missing, instead of showing empty tables until
  someone manually re-runs every fetch button by hand. Only fills in
  files that don't already exist locally; never overwrites a file the
  current container already has (that file is presumed at least as
  fresh as whatever's on GitHub, since nothing else writes to this
  container's local disk).

Reuses the SAME [github_data] secrets (token/repo) as user_store.py and
config.py -- no new setup required. Files live under a `market_data/`
prefix inside that same private repo (configurable via the
`market_data_prefix` secrets key) so they don't collide with
users.json/watchlist.json.

Purely additive/opt-in: with no [github_data] section configured, both
push_all()/push_category() and pull_all() are no-ops, and the app
behaves exactly as it always has (local-only CSVs, wiped on restart,
regenerated by clicking the fetch buttons again).
"""

import os

from config import DATA_DIR
import github_json_store

# Every local data/<category>/ folder a fetch script writes CSVs into.
# Keep this in sync with price_data.py/dividend_data.py/institutional_data.py/
# market_value_data.py/news_data.py's own _csv_path()-style helpers.
CATEGORIES = ["prices", "dividends", "institutional", "market_value", "news"]


def _github_config():
    """Same idea as user_store._github_config()/config._github_config(),
    but reads `market_data_prefix` instead of `path`/`watchlist_path`.
    Lazily imports streamlit so this module stays importable from plain
    `python main.py`-style runs even if streamlit isn't installed there;
    returns None (no-op everywhere below) whenever [github_data] isn't
    configured or streamlit can't be imported."""
    try:
        import streamlit as st
        section = st.secrets["github_data"]
        return section["token"], section["repo"], section.get("market_data_prefix", "market_data")
    except Exception:
        return None


def _local_dir(category):
    return os.path.join(DATA_DIR, category)


def push_category(category):
    """Uploads every local CSV under data/<category>/ to GitHub. Meant to
    be called once, right after a fetch script for that category
    finishes successfully. No-op (returns immediately) if GitHub-backed
    storage isn't configured, or if there's no local folder for this
    category yet (nothing fetched). Raises GitHubStorageError on a real
    failure -- callers should catch it and show a warning rather than
    treat it as fatal, since the local fetch itself already succeeded by
    the time this runs."""
    cfg = _github_config()
    if cfg is None:
        return
    token, repo, prefix = cfg
    local_dir = _local_dir(category)
    if not os.path.isdir(local_dir):
        return
    for filename in sorted(os.listdir(local_dir)):
        if not filename.endswith(".csv"):
            continue
        with open(os.path.join(local_dir, filename), encoding="utf-8-sig") as f:
            content = f.read()
        remote_path = f"{prefix}/{category}/{filename}"
        github_json_store.save_text_with_retry(
            token, repo, remote_path, content,
            commit_message=f"Update {category}/{filename}",
        )


def push_all():
    """push_category() for every category -- used after `python main.py`
    with no flags (fetches prices/dividends/news) and after the app's
    "一鍵抓取全部資料" button."""
    for category in CATEGORIES:
        push_category(category)


_pulled_this_process = False


def pull_all():
    """Restores any GitHub-backed CSV that's missing from this
    container's local disk. Safe to call every Streamlit rerun -- the
    module-level latch below means the actual GitHub calls only happen
    once per running process (the first rerun after a fresh container
    start), exactly like config.WATCHLIST's own import-time load.
    Swallows GitHubStorageError per-category (a transient error or an
    unconfigured/empty category shouldn't block startup) rather than
    raising -- there's no UI to show an error in this early, and a
    failed restore just means the user sees empty tables and can
    re-fetch, same as before this feature existed."""
    global _pulled_this_process
    if _pulled_this_process:
        return
    _pulled_this_process = True
    cfg = _github_config()
    if cfg is None:
        return
    token, repo, prefix = cfg
    for category in CATEGORIES:
        try:
            filenames = github_json_store.list_dir(token, repo, f"{prefix}/{category}")
        except github_json_store.GitHubStorageError:
            continue
        if not filenames:
            continue
        local_dir = _local_dir(category)
        for filename in filenames:
            if not filename.endswith(".csv"):
                continue
            local_path = os.path.join(local_dir, filename)
            if os.path.exists(local_path):
                continue  # this container already has it -- don't clobber
            try:
                content, _ = github_json_store.read_text(token, repo, f"{prefix}/{category}/{filename}")
            except github_json_store.GitHubStorageError:
                continue
            if content is None:
                continue
            os.makedirs(local_dir, exist_ok=True)
            with open(local_path, "w", encoding="utf-8-sig") as f:
                f.write(content)
